import React, { useState } from 'react';
import { useAppStore } from '../store/appStore';
import type { StoreTask } from '../types';
import { 
  CheckCircle2, 
  Camera, 
  ArrowRight, 
  ShieldCheck, 
  RotateCcw,
  Check,
  UserCheck
} from 'lucide-react';
import confetti from 'canvas-confetti';

export const TasksPage: React.FC = () => {
  const { 
    tasks, 
    updateTaskStatus, 
    verifyTaskWithCamera 
  } = useAppStore();

  const [activeTaskDetail, setActiveTaskDetail] = useState<StoreTask | null>(tasks[0]);

  const handleVerify = (taskId: string) => {
    verifyTaskWithCamera(taskId);
    try {
      confetti({ particleCount: 40, spread: 60, origin: { y: 0.7 } });
    } catch (e) {
      // fallback
    }
  };

  const getStatusBadge = (status: StoreTask['status']) => {
    switch (status) {
      case 'Pending':
        return <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-slate-100 text-slate-700">Pending</span>;
      case 'Assigned':
        return <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-blue-50 text-blue-700 border border-blue-200">Assigned</span>;
      case 'In Progress':
        return <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-amber-50 text-amber-700 border border-amber-200">In Progress</span>;
      case 'Completed':
        return <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-purple-50 text-purple-700 border border-purple-200">Awaiting Cam AI</span>;
      case 'Verified':
        return (
          <span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-emerald-50 text-emerald-700 border border-emerald-200 flex items-center gap-1">
            <CheckCircle2 className="w-3.5 h-3.5" /> Action Verified ✓
          </span>
        );
    }
  };

  const currentTask = activeTaskDetail || tasks[0];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold text-slate-900 tracking-tight flex items-center gap-2">
            <span>Tasks & Closed-Loop Camera Verification</span>
            <span className="text-xs px-2.5 py-0.5 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200 font-semibold">
              Detect → Alert → Assign → Complete → Verify
            </span>
          </h1>
          <p className="text-xs text-slate-500 mt-1">
            Staff tasks generated by AI detection, followed by computer vision confirmation of physical execution.
          </p>
        </div>
      </div>

      {/* Verification Lifecycle Stepper */}
      <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-card">
        <div className="flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-emerald-50 text-emerald-600">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-slate-900">Closed-Loop Verification Model</h2>
              <p className="text-xs text-slate-500">Physical restock operations are validated by ceiling camera neural models before resolution.</p>
            </div>
          </div>

          <div className="flex items-center gap-2 text-xs font-semibold text-slate-600">
            <span className="px-2.5 py-1 rounded bg-slate-100">1. Detect</span>
            <ArrowRight className="w-3 h-3 text-slate-400" />
            <span className="px-2.5 py-1 rounded bg-slate-100">2. Alert</span>
            <ArrowRight className="w-3 h-3 text-slate-400" />
            <span className="px-2.5 py-1 rounded bg-slate-100">3. Assign</span>
            <ArrowRight className="w-3 h-3 text-slate-400" />
            <span className="px-2.5 py-1 rounded bg-slate-100">4. Complete</span>
            <ArrowRight className="w-3 h-3 text-slate-400" />
            <span className="px-2.5 py-1 rounded bg-emerald-50 text-emerald-700 border border-emerald-200 font-bold">5. Camera Verify</span>
          </div>
        </div>
      </div>

      {/* Grid: Task Table (Left) + Verification Inspector (Right) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Table */}
        <div className="lg:col-span-7 bg-white rounded-xl border border-slate-200 p-5 shadow-card space-y-4">
          <div className="flex items-center justify-between pb-3 border-b border-slate-100">
            <h2 className="text-sm font-bold text-slate-900">Active Operational Tasks</h2>
            <span className="text-xs text-slate-400 font-mono">{tasks.length} Tasks</span>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-slate-50 text-slate-500 uppercase font-semibold text-[10px] tracking-wider border-b border-slate-200">
                <tr>
                  <th className="py-2.5 px-3">Task</th>
                  <th className="py-2.5 px-3">Location</th>
                  <th className="py-2.5 px-3">Priority</th>
                  <th className="py-2.5 px-3">Status</th>
                  <th className="py-2.5 px-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {tasks.map((task) => {
                  const isSelected = currentTask.id === task.id;
                  return (
                    <tr
                      key={task.id}
                      onClick={() => setActiveTaskDetail(task)}
                      className={`cursor-pointer transition ${
                        isSelected ? 'bg-emerald-50/70 border-l-2 border-emerald-600' : 'hover:bg-slate-50'
                      }`}
                    >
                      <td className="py-3 px-3">
                        <span className="font-bold text-slate-900 block">{task.title}</span>
                        <span className="text-[10px] text-slate-500">{task.assignee || 'Unassigned'}</span>
                      </td>
                      <td className="py-3 px-3 text-slate-600">{task.location}</td>
                      <td className="py-3 px-3 font-semibold">
                        <span className={task.priority === 'High' ? 'text-rose-600' : 'text-amber-600'}>
                          {task.priority}
                        </span>
                      </td>
                      <td className="py-3 px-3">{getStatusBadge(task.status)}</td>
                      <td className="py-3 px-3 text-right">
                        <div className="flex items-center justify-end gap-1.5" onClick={(e) => e.stopPropagation()}>
                          {task.status === 'Pending' && (
                            <button
                              onClick={() => updateTaskStatus(task.id, 'Assigned')}
                              className="px-2.5 py-1 rounded bg-blue-600 hover:bg-blue-700 text-white font-bold text-[11px] shadow-sm"
                            >
                              Assign
                            </button>
                          )}
                          {task.status === 'Assigned' && (
                            <button
                              onClick={() => updateTaskStatus(task.id, 'In Progress')}
                              className="px-2.5 py-1 rounded bg-amber-500 hover:bg-amber-600 text-white font-bold text-[11px] shadow-sm"
                            >
                              Start
                            </button>
                          )}
                          {task.status === 'In Progress' && (
                            <button
                              onClick={() => updateTaskStatus(task.id, 'Completed')}
                              className="px-2.5 py-1 rounded bg-purple-600 hover:bg-purple-700 text-white font-bold text-[11px] shadow-sm"
                            >
                              Complete
                            </button>
                          )}
                          {task.status === 'Completed' && (
                            <button
                              onClick={() => handleVerify(task.id)}
                              className="px-2.5 py-1 rounded bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-[11px] shadow-sm flex items-center gap-1"
                            >
                              <Camera className="w-3 h-3" />
                              <span>Verify</span>
                            </button>
                          )}
                          {task.status === 'Verified' && (
                            <span className="text-[11px] text-emerald-700 font-bold">✓ Verified</span>
                          )}
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>

        {/* Right: Inspector */}
        <div className="lg:col-span-5 bg-white rounded-xl border border-slate-200 p-5 shadow-card space-y-4 flex flex-col justify-between">
          <div>
            <div className="flex items-start justify-between pb-3 border-b border-slate-100">
              <div>
                <span className="text-[10px] font-mono font-bold text-emerald-700 uppercase tracking-wider block">
                  Closed-Loop Inspector
                </span>
                <h3 className="text-base font-bold text-slate-900 mt-0.5">{currentTask.title}</h3>
                <span className="text-xs text-slate-500">{currentTask.location}</span>
              </div>
              {getStatusBadge(currentTask.status)}
            </div>

            {/* Stepper */}
            <div className="my-4 p-3 rounded-lg bg-slate-50 border border-slate-200">
              <span className="text-[10px] uppercase font-bold text-slate-500 block mb-2">
                Operational Task Lifecycle
              </span>
              <div className="grid grid-cols-4 gap-1 text-center text-[10px]">
                {['Pending', 'Assigned', 'Completed', 'Verified'].map((step, idx) => {
                  const isCurrent = currentTask.status === step;
                  const isDone = 
                    (currentTask.status === 'Assigned' && idx <= 1) ||
                    (currentTask.status === 'In Progress' && idx <= 1) ||
                    (currentTask.status === 'Completed' && idx <= 2) ||
                    (currentTask.status === 'Verified');

                  return (
                    <div
                      key={step}
                      className={`p-1.5 rounded font-semibold ${
                        isCurrent
                          ? 'bg-emerald-600 text-white font-bold'
                          : isDone
                          ? 'bg-emerald-50 text-emerald-800 border border-emerald-200'
                          : 'bg-white border border-slate-200 text-slate-500'
                      }`}
                    >
                      {step}
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Verification Detail Box */}
            <div className={`p-4 rounded-xl border ${
              currentTask.status === 'Verified' ? 'bg-emerald-50/70 border-emerald-200' : 'bg-slate-50 border-slate-200'
            }`}>
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-bold text-slate-900 flex items-center gap-1.5">
                  <Camera className="w-4 h-4 text-emerald-600" />
                  <span>Camera Optical Proof</span>
                </span>
                {currentTask.status === 'Verified' && (
                  <span className="text-[10px] px-2 py-0.5 rounded bg-emerald-100 text-emerald-800 font-mono font-bold">
                    Confidence: 98.4%
                  </span>
                )}
              </div>

              <p className="text-xs text-slate-600 leading-relaxed">
                {currentTask.verificationMessage || 
                  'Awaiting physical task completion. Once marked completed, overhead ceiling camera automatically evaluates shelf fill percentage.'}
              </p>
            </div>
          </div>

          <div className="pt-2">
            {currentTask.status !== 'Verified' ? (
              <button
                onClick={() => handleVerify(currentTask.id)}
                className="w-full py-2.5 px-4 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs shadow-sm transition flex items-center justify-center gap-2"
              >
                <Camera className="w-4 h-4" />
                <span>Simulate Camera Verification</span>
              </button>
            ) : (
              <button
                onClick={() => updateTaskStatus(currentTask.id, 'Assigned')}
                className="w-full py-2 px-3 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold transition flex items-center justify-center gap-1"
              >
                <RotateCcw className="w-3.5 h-3.5" />
                <span>Reset Lifecycle</span>
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
